# Use an existing base image
FROM node:latest

# Add a healthcheck (default every 30 secs)
# HEALTHCHECK CMD curl http://localhost:1880/ || exit 1

# Open ports 41900 and 41901
EXPOSE 41900 41901

# Update and upgrade packages
RUN apt-get update && apt-get upgrade -y

# Install necessary packages
RUN apt-get install -y socat iproute2 curl iputils-ping nano jq 

# Install Joplin
RUN NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin && ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin

RUN mkdir -p /data && chmod 755 /data

COPY entrypoint.sh /data/entrypoint.sh
RUN chmod +x /data/entrypoint.sh

ENTRYPOINT ["/data/entrypoint.sh"]