# Use an existing base image
FROM node:latest

# Open ports 41900 and 41901
EXPOSE 41900 41901

# Update and upgrade packages
RUN apt-get update && apt-get upgrade -y

# Install necessary packages
RUN apt-get install -y socat iproute2 curl iputils-ping nano

# Install Joplin
RUN NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin && ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin

# Start Joplin server and socat
CMD joplin server start && socat tcp-listen:41900,reuseaddr,fork tcp:localhost:41184
