name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  #push:
 #   branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Copy to Local Repo
        run: |
            cp -R wenLiangcan/chatgpt-telegram-bot/* ./
      - name: Copy .env to Repo Folder
        run: cp .env ./chatgpt-telegram-bot/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/chatgpt-telegram-bot:latest .

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/chatgpt-telegram-bot:latest
