name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    env:
      GITHUB_TOKEN: ${{ secrets.GITTOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_BRANCH: main # branch to fetch, default: current workflow branch (usually it is repository default branch (usually it is master))
          INPUTS_EMAIL: actions@github.com # user.email to merge, default: actions@github.com
          INPUTS_NAME: git merge upstream # user.name to merge, default: git merge upstream
          INPUTS_REPOSITORY: wenLiangcan/chatgpt-telegram-bot # repository from fetch, required
          INPUTS_URL: https://github.com # fetch repository url, default https://github.com
        uses: rekgrpth/git-fetch-upstream-merge-push-shell-action@v1

